language: java
jdk:
  - oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
  - $HOME/.m2
  
script: "mvn clean install"

before_deploy:
  - export RELEASE_FILE=$(ls target/cognizant-intelligent-test-scripter-*.*)
  
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:  $RELEASE_FILE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
