language: java
sudo: false
dist: trusty
jdk: oraclejdk11
addons:
  apt:
    packages:
      - openjdk11

cache:
  directories:
  - $HOME/.m2
  
install: true

script: "mvn clean install"

before_deploy:
  - export RELEASE_FILE=$(ls Dist/target/cognizant-intelligent-test-scripter-*.zip)

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:  $RELEASE_FILE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
