language: java
before_script:
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  include:
  
  - stage: 🚫 jdk.java.net - Archived OpenJDK General-Availability Releases
    env: JDK=11 🚫
    script: source ./install-jdk.sh --feature 11

cache:
  directories:
  - $HOME/.m2
  
install: true

script: "mvn clean install"

before_deploy:
  - export RELEASE_FILE=$(ls Dist/target/cognizant-intelligent-test-scripter-*.zip)

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:  $RELEASE_FILE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
