# This workflow will build CITS package using Maven and then publish it as an artifact when a release is created

name: CITS Packaging

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github 
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn clean install
    
    - name: Upload tool setup file
      uses: actions/upload-artifact@v3.0.0
      with:
       name: Cognizant-Intelligent-Test-Scripter-Setup
       path: Dist/target/*.zip 
